services:
  gateway:
    build:
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway ## Dockerfile에도 Command가 있으면 docker-compose.yml의 Command로 오버라이드 됨.
    env_file: ## 환경변수 파일 경로 입력
      - ./apps/gateway/.env
    ports:
      - "3000:3000" ## 내 컴퓨터 포트:도커 컨테이너 안 포트
    volumes: ## Dockerfile은 빌드할 때만 동작하므로, 빌드 후에 변경사항이 적용되지 않음. 따라서 volumes를 사용하여 런타임에도 변경사항이 동기화되도록 함.
      - .:/usr/src/app ## 내 컴퓨터 경로(.):컨테이너 안 경로(/usr/src/app), 내 컴퓨터 경로(.)의 모든 내용을 컨테이너 안 경로에 동기화시키겠다. 
      - /usr/src/app/node_modules ## 콜론을 안넣고 도커 경로만 입력하면 해당 경로 내용은 동기화를 안하겠다는 의미, 
      ## 내 컴퓨터 OS에 맞는 node_modules이 생성됐을 것이기 때문에 도커랑 OS가 다를 수도 있으므로 동기화시키면 안된다.

  user:
    build:
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: pnpm run start:dev user
    depends_on:
      postgres_user:
        condition: service_healthy ## postgres_user가 정상적으로 실행되면 user가 실행됨.
    env_file: 
      - ./apps/user/.env
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules 
  postgres_user:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6001:5432"
    volumes: ## 도커 컨테이너 내 데이터베이스 데이터(/var/lib/postgresql/data)를 저장할 내 컴퓨터 폴더(./postgres/user)를 지정
      - ./postgres/user:/var/lib/postgresql/data ## 도커 킬 때마다 데이터 사라지기 때문에 내 컴퓨터에 저장해야 함.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s ## 5초마다 실행
      timeout: 5s ## 5초 기다리고 실패하면 재시도
      retries: 10 ## 10번까지 시도
      start_period: 5s ## 도커 이미지 빌드하고 5초 기다리고 healthcheck를 실행함.

  product:
    build:
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: pnpm run start:dev product
    depends_on:
      postgres_product:
        condition: service_healthy
    env_file:
      - ./apps/product/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres_product:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6002:5432"
    volumes:
      - ./postgres/product:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  order:
    build:
      dockerfile: ./apps/order/Dockerfile
      target: development
    command: pnpm run start:dev order
    depends_on:
      mongo_order:
        condition: service_healthy
    env_file:
      - ./apps/order/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo_order:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - '6003:27017'
    volumes:
      - ./mongo/order:/data/lib
    command: mongod --quiet --logpath /dev/null ## mongodb 실행시킬 때 로그가 너무 많이 나오기 때문에 /dev/null 경로로 logpath 설정하면 로그 자동으로 삭제된다.
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  payment:
    build:
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: pnpm run start:dev payment
    depends_on:
      postgres_payment:
        condition: service_healthy
    env_file:
      - ./apps/payment/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres_payment:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6004:5432"
    volumes:
      - ./postgres/payment:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  notification:
    build:
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: pnpm run start:dev notification
    depends_on:
      mongo_notification:
        condition: service_healthy
    env_file:
      - ./apps/notification/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo_notification:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - '6005:27017'
    volumes:
      - ./mongo/notification:/data/lib
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s