services:
  user:
    build:
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: pnpm run start:dev user ## Dockerfile에도 Command가 있으면 docker-compose.yml의 Command로 오버라이드 됨.
    depends_on:
      postgres_user:
        condition: service_healthy ## postgres_user가 정상적으로 실행되면 user가 실행됨.
    env_file: ## 환경변수 파일 경로 입력
      - ./apps/user/.env
    ports:
      - "3001:3000" ## 내 컴퓨터 포트:도커 컨테이너 안 포트
    volumes: ## Dockerfile은 빌드할 때만 동작하므로, 빌드 후에 변경사항이 적용되지 않음. 따라서 volumes를 사용하여 런타임에도 변경사항이 동기화되도록 함.
      - .:/user/src/app ## 내 컴퓨터 경로(.):컨테이너 안 경로(/user/src/app), 내 컴퓨터 경로(.)의 모든 내용을 컨테이너 안 경로에 동기화시키겠다. 
      - /user/src/app/node_modules ## 콜론을 안넣고 도커 경로만 입력하면 해당 경로 내용은 동기화를 안하겠다는 의미, 
      ## 내 컴퓨터 OS에 맞는 node_modules이 생성됐을 것이기 때문에 도커랑 OS가 다를 수도 있으므로 동기화시키면 안된다.

  postgres_user:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6001:5432"
    volumes: ## 도커 컨테이너 내 데이터베이스 데이터(/var/lib/postgresql/data)를 저장할 내 컴퓨터 폴더(./postgres/user)를 지정
      - ./postgres/user:/var/lib/postgresql/data ## 도커 킬 때마다 데이터 사라지기 때문에 내 컴퓨터에 저장해야 함.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s ## 5초마다 실행
      timeout: 5s ## 5초 기다리고 실패하면 재시도
      retries: 10 ## 10번까지 시도
      start_period: 5s ## 도커 이미지 빌드하고 5초 기다리고 healthcheck를 실행함.