apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  labels:
    app: payment
type: Opaque
data:
  DB_HOST: '{{ .Values.payment.db_host | b64enc }}'
  DB_USER: '{{ .Values.payment.db_user | b64enc }}'
  DB_PASSWORD: '{{ .Values.payment.db_password | b64enc }}'
  DB_NAME: '{{ .Values.payment.db_name | b64enc }}'
