apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  labels:
    app: product
type: Opaque
data:
  DB_HOST: '{{ .Values.product.db_host | b64enc }}'
  DB_USER: '{{ .Values.product.db_user | b64enc }}'
  DB_PASSWORD: '{{ .Values.product.db_password | b64enc }}'
  DB_NAME: '{{ .Values.product.db_name | b64enc }}'
