apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  labels:
    app: user
type: Opaque
data:
  DB_HOST: '{{ .Values.user.db_host | b64enc }}'
  DB_USER: '{{ .Values.user.db_user | b64enc }}'
  DB_PASSWORD: '{{ .Values.user.db_password | b64enc }}'
  DB_NAME: '{{ .Values.user.db_name | b64enc }}'
